# Generated by Django 2.2.11 on 2020-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='furt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='shopme/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
