# Generated by Django 2.2.11 on 2020-04-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0002_auto_20200411_1147'),
        ('shopme', '0003_auto_20200329_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseperuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopme.product')),
                ('userInstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginsystem.newuser')),
            ],
        ),
    ]
